spring.application.name=skill-9
spring.datasource.url=jdbc:mysql://localhost:3306/sec2
spring.datasource.username=root
spring.datasource.password=Chanikya_21

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=2026